# Generated by Django 5.2.17 on 2026-09-20 22:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(max_length=60)),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.CharField(max_length=40)),
                ('summary', models.CharField(max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('corrective', '纠正措施'), ('preventive', '预防措施')], default='corrective', max_length=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_progress', '执行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_actions', to=settings.AUTH_USER_MODEL)),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '纠正预防措施',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CompletionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('attachment_ref', models.CharField(blank=True, max_length=300)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_status', models.CharField(choices=[('pending', '待批准'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_evidences', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_evidences', to=settings.AUTH_USER_MODEL)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='quality.correctiveaction')),
            ],
            options={
                'verbose_name': '完成证据',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('batch_no', models.CharField(blank=True, max_length=60)),
                ('severity', models.CharField(choices=[('minor', '一般'), ('major', '主要'), ('critical', '严重')], default='major', max_length=10)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('open', '已发起'), ('investigating', '调查中'), ('closed', '已关闭'), ('reopened', '重新打开')], default='open', max_length=20)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_deviations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '偏差',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='deviation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='quality.deviation'),
        ),
        migrations.CreateModel(
            name='EffectivenessBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_days', models.PositiveIntegerField()),
                ('min_sample_size', models.PositiveIntegerField()),
                ('max_extensions', models.PositiveIntegerField(default=3)),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='baseline', to='quality.correctiveaction')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_baselines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '有效性判定基线',
            },
        ),
        migrations.CreateModel(
            name='EffectivenessEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', '待观察（措施未完成）'), ('observing', '观察中'), ('extended', '观察已延长（数据不足）'), ('data_insufficient', '数据不足（达延长上限）'), ('ready', '可提交评审'), ('in_review', '评审中'), ('effective', '判定有效'), ('ineffective', '判定无效'), ('closed', '已关闭'), ('reopened', '因相关偏差重开')], default='pending', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('effective', '有效'), ('ineffective', '无效')], max_length=12, null=True)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('extension_count', models.PositiveIntegerField(default=0)),
                ('is_current', models.BooleanField(default=True)),
                ('conclusion_note', models.CharField(blank=True, max_length=1000)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='quality.correctiveaction')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_evaluations', to=settings.AUTH_USER_MODEL)),
                ('trigger_deviation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triggered_evaluations', to='quality.deviation')),
            ],
            options={
                'verbose_name': '有效性判定版本',
                'ordering': ['action', '-version'],
                'unique_together': {('action', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ConflictOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stance', models.CharField(choices=[('supports_effective', '支持有效'), ('challenges', '质疑有效性'), ('abstain', '中立/保留')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opinions', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='quality.effectivenessevaluation')),
            ],
            options={
                'verbose_name': '冲突意见',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('metric_type', models.CharField(choices=[('mean', '均值'), ('rate', '比率'), ('count', '计数')], default='mean', max_length=10)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('direction', models.CharField(choices=[('decrease', '越低越好'), ('increase', '越高越好')], default='decrease', max_length=10)),
                ('baseline_value', models.FloatField()),
                ('target_value', models.FloatField()),
                ('fail_condition', models.CharField(choices=[('none', '无聚合失败条件'), ('aggregate_threshold', '聚合值越过阈值'), ('individual_breach', '单点越限')], default='aggregate_threshold', max_length=20)),
                ('fail_threshold', models.FloatField(blank=True, null=True)),
                ('allowed_breaches', models.PositiveIntegerField(default=0)),
                ('min_sample_size', models.PositiveIntegerField(blank=True, help_text='为空时使用基线全局最小样本量', null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='quality.correctiveaction')),
            ],
            options={
                'verbose_name': '观察指标',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MetricObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, max_length=60)),
                ('observed_at', models.DateTimeField()),
                ('value', models.FloatField()),
                ('sample_count', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='quality.metric')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '指标观察数据',
                'ordering': ['observed_at'],
            },
        ),
        migrations.CreateModel(
            name='RootCauseHypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('man', '人员'), ('machine', '设备'), ('material', '物料'), ('method', '方法'), ('environment', '环境'), ('measurement', '测量')], max_length=15)),
                ('description', models.TextField()),
                ('supporting_evidence', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deviation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to='quality.deviation')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_hypotheses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '根因假设',
                'ordering': ['-is_confirmed', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve_close', '批准有效/关闭'), ('reject', '退回（无效）'), ('withdrawn', '撤回前序签署')], max_length=15)),
                ('reason', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('signoff_version', models.PositiveIntegerField(default=1)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoffs', to='quality.effectivenessevaluation')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signoffs', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='quality.signoff')),
            ],
            options={
                'verbose_name': '质量签署',
                'ordering': ['-signoff_version', '-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('quality', '质量角色'), ('owner', '措施责任人'), ('investigator', '调查人员')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户角色',
            },
        ),
        migrations.CreateModel(
            name='RelatedDeviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_note', models.CharField(blank=True, max_length=500)),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_deviations', to='quality.correctiveaction')),
                ('deviation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_to_actions', to='quality.deviation')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_related_deviations', to=settings.AUTH_USER_MODEL)),
                ('reopened_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopen_links', to='quality.effectivenessevaluation')),
            ],
            options={
                'verbose_name': '相关偏差关联',
                'unique_together': {('action', 'deviation')},
            },
        ),
    ]
