# Generated by Django 5.2.17 on 2026-09-20 22:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('action', models.CharField(max_length=64, verbose_name='操作')),
                ('entity_type', models.CharField(max_length=64, verbose_name='对象类型')),
                ('entity_id', models.CharField(max_length=64, verbose_name='对象ID')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='摘要')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='明细')),
                ('actor', models.ForeignKey(blank=True, help_text='为空表示系统行为', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CAPAAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='措施编号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='措施内容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待批准'), ('approved', '已批准(执行中)'), ('monitoring', '措施完成·观察中'), ('pending_review', '待有效性评审'), ('closed_effective', '已关闭·有效'), ('closed_ineffective', '已关闭·无效'), ('reopened', '已重开')], default='draft', max_length=32, verbose_name='状态')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='要求完成日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_actions', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='偏差编号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('severity', models.CharField(choices=[('minor', '轻微'), ('major', '主要'), ('critical', '严重')], default='minor', max_length=16, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('open', '未处理'), ('investigating', '调查中'), ('capa_in_progress', 'CAPA 执行中'), ('monitoring', '效果观察中'), ('closed', '已关闭')], default='open', max_length=32, verbose_name='状态')),
                ('occurred_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='发生日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('linked_action', models.ForeignKey(blank=True, help_text='若该偏差是某措施观察期内的复发/相关偏差, 关联后将自动重开判定', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_deviations', to='capa.capaaction', verbose_name='关联措施')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='capaaction',
            name='deviation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capa_actions', to='capa.deviation', verbose_name='来源偏差'),
        ),
        migrations.CreateModel(
            name='EffectivenessEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本')),
                ('result', models.CharField(choices=[('effective', '有效'), ('ineffective', '无效'), ('inconclusive', '数据不足·继续观察'), ('extended', '数据不足·已延长观察'), ('reopened', '因新偏差重开')], max_length=16, verbose_name='结论')),
                ('rationale', models.JSONField(default=list, verbose_name='判定理由')),
                ('metrics_summary', models.JSONField(default=dict, verbose_name='指标摘要')),
                ('sample_size', models.PositiveIntegerField(default=0, verbose_name='窗口内样本量')),
                ('eligible_for_review', models.BooleanField(default=False, verbose_name='可提交评审')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='判定时间')),
                ('is_current', models.BooleanField(default=True, verbose_name='当前版本')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='capa.capaaction', verbose_name='措施')),
                ('created_by', models.ForeignKey(blank=True, help_text='为空表示系统定时评估产生', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='判定人')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='EffectivenessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('observation_start', models.DateField(verbose_name='观察开始日')),
                ('observation_end', models.DateField(verbose_name='观察截止日')),
                ('min_sample_size', models.PositiveIntegerField(default=3, verbose_name='最小样本量')),
                ('extension_count', models.PositiveIntegerField(default=0, verbose_name='已延长次数')),
                ('is_frozen', models.BooleanField(default=False, verbose_name='已固化')),
                ('is_current', models.BooleanField(default=True, verbose_name='当前版本')),
                ('change_reason', models.CharField(blank=True, max_length=255, verbose_name='版本说明')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='批准时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='capa.capaaction', verbose_name='措施')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='文件/记录引用')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('status', models.CharField(choices=[('submitted', '待审核'), ('approved', '已批准'), ('rejected', '已驳回')], default='submitted', max_length=16, verbose_name='状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='capa.capaaction', verbose_name='措施')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_evidence', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_evidence', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='指标名')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='单位')),
                ('baseline', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='基线值')),
                ('target', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='目标值')),
                ('direction', models.CharField(choices=[('increase', '越高越好'), ('decrease', '越低越好')], max_length=16, verbose_name='改善方向')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='capa.effectivenessplan', verbose_name='所属计划')),
            ],
        ),
        migrations.CreateModel(
            name='MetricReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=64, verbose_name='批号')),
                ('value', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='读数')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='采集时间')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='capa.observationmetric', verbose_name='指标')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='FailureCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<=')], max_length=8, verbose_name='比较符')),
                ('threshold', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='阈值')),
                ('description', models.CharField(max_length=255, verbose_name='条件说明')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_conditions', to='capa.effectivenessplan', verbose_name='所属计划')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_conditions', to='capa.observationmetric', verbose_name='指标')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stance', models.CharField(choices=[('agree', '同意'), ('disagree', '反对')], max_length=16, verbose_name='立场')),
                ('comment', models.TextField(blank=True, verbose_name='意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='capa.effectivenessevaluation', verbose_name='判定')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评审人')),
            ],
        ),
        migrations.CreateModel(
            name='RootCauseHypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(verbose_name='假设内容')),
                ('status', models.CharField(choices=[('proposed', '已提出'), ('confirmed', '已确认'), ('rejected', '已排除')], default='proposed', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='提出人')),
                ('deviation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to='capa.deviation', verbose_name='偏差')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='capaaction',
            name='hypothesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='capa.rootcausehypothesis', verbose_name='针对的根因假设'),
        ),
        migrations.CreateModel(
            name='SignOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('decision', models.CharField(choices=[('close_effective', '签署关闭·有效'), ('close_ineffective', '签署关闭·无效'), ('withdraw', '撤回签署')], max_length=32, verbose_name='决定')),
                ('comment', models.TextField(blank=True, verbose_name='签署意见')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='签署时间')),
                ('state', models.CharField(choices=[('active', '生效中'), ('withdrawn', '已撤回')], default='active', max_length=16, verbose_name='状态')),
                ('withdrawn_reason', models.TextField(blank=True, verbose_name='撤回理由')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='撤回时间')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoffs', to='capa.capaaction', verbose_name='措施')),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signoffs', to='capa.effectivenessevaluation', verbose_name='依据的判定')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='capa.signoff', verbose_name='取代的签署')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='签署人')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='effectivenessevaluation',
            constraint=models.UniqueConstraint(fields=('action', 'version'), name='uniq_evaluation_version_per_action'),
        ),
        migrations.AddConstraint(
            model_name='effectivenessplan',
            constraint=models.UniqueConstraint(fields=('action', 'version'), name='uniq_plan_version_per_action'),
        ),
        migrations.AddConstraint(
            model_name='reviewopinion',
            constraint=models.UniqueConstraint(fields=('evaluation', 'user'), name='uniq_opinion_per_user_per_evaluation'),
        ),
    ]
